### ISSUE TITLE
Ошибка в документации MetaHash-Supply 

### ISSUE THREAD

**Issue by xboston** [metahashorg/MetaHash#1]
На странице https://github.com/metahashorg/MetaHash/wiki/MetaHash-Supply ошибка в последнем параграфе:
```
Return:
{
  "address_balance_decimals" : "276000000000000"
}
```

По факту возвращается только число, без json конструкции с address_balance_decimals.

**Comment by Nikitaempower** [comment]
В документацию были внесены соответствующие правки. Спасибо.
