### ISSUE TITLE
Торрент-нода (Node-InfrastructureTorrent) не умеет работать с secp256r1 типом ключа

### ISSUE THREAD

**Issue by xboston** [metahashorg/MetaHash#16]
Эти ключи начинаются на  `30770201010420`
И работает с `30740201010420`

При неверном типе ключа ругается на 
```
ERROR 139849546231360: Incorrect private key or address. Error at file /home/user/torrent_w_node/src/PrivateKey.cpp line 38
```

**Comment by xboston** [comment]
Вот пруф https://github.com/metahashorg/Node-InfrastructureTorrent/blob/master/src/PrivateKey.cpp#L28

**Comment by feruzm** [comment]
Nikolay and I found that there might be mix of `256k1` and `256r1` functions on private key generation.

**Comment by xboston** [comment]
питон делает k1:
https://github.com/metahashorg/crypt_example_py/blob/master/crypt_example_bin.py#L231

php делает r1:
https://github.com/metahashorg/crypt_example_php/blob/master/crypt_example.php#L63

sh делает k1:
https://github.com/metahashorg/crypt_example_sh/blob/master/metahash_cli_bin.sh#L34

**Comment by Nikitaempower** [comment]
@xboston  Благодарим за информацию.  Приняли во внимание.
