### ISSUE TITLE
Разные параметры методов получения запросов блоков у Torrent и InfrastructureTorrent нод

### ISSUE THREAD

**Issue by xboston** [metahashorg/MetaHash#17]
При запросе в текущим торрент-нодам (http://tor.net-main.metahashnetwork.com:5795) нормально работает запрос:
```
{
    "id": 1,
    "version": "1.0.0",
    "method": "get-block-by-number",
    "params":{
      "number": 475345,
      "type": 1, 
      "beginTx": 1,
      "countTxs": 5
    }
}
```

При выполнении его же к InfrastructureTorrent в ответ приходит ничего, ни ошибки ни ответа.
Всё из-за изменившегося параметра `type`, теперь его надо передавать строкой (https://github.com/metahashorg/Node-Torrent/wiki/Usage#get-block-by-number):
>type - type of requested info: full - полный дамп, hashes - только хэши, small - минимум информации о заголовке блока, simple или отсутствует - только заголовок блока.

Получается один и тот же метод с одним и тем же результатом имеет один отличающийся параметр, это очень нехорошо и пусть к куче костылей и несовместимостей.

**Comment by Nikitaempower** [comment]
Благодарим за Ваш вопрос, @xboston 

Торрент не поддерживает типы блока full и hashes.

Внесли необходимые правки в документацию.
