### ISSUE TITLE
Скрипт crypt_example_sh не работает с mainnet

### ISSUE THREAD

**Issue by xboston** [metahashorg/MetaHash#18]
Этот https://github.com/metahashorg/crypt_example_sh на текущий момент бесполезен для работы с основной сетью.
 
Указание методов в таком виде `$torrent_node:$node_port/fetch-history` работает только в тестнете, для майннета нужно метод указывать в POST параметрах.

**Comment by Nikitaempower** [comment]
Благодарим за Ваш вопрос. 

Произвели проверку. Скрипт полностью рабочий.
