### ISSUE TITLE
Не работает fetch-history-filter

### ISSUE THREAD

**Issue by xboston** [metahashorg/MetaHash#20]
Пробую https://github.com/metahashorg/metahash-fullnode-client/wiki/Usage#fetch-history-filter

```JSON
POST http://tor.net-main.metahashnetwork.com:5795
{
    "id": 1,
    "jsonrpc": "2.0",
    "method": "fetch-history",
    "params": {
        "address": "0x00fa2a5279f8f0fd2f0f9d3280ad70403f01f9d62f52373833",
        "filters": [
            {
                "isForging": true
            }
        ]
    }
}
// в ответе обычная транзакция, не форджинговая
{
  "id": 1,
  "result": [
    {
      "from": "0x002a3e8f2714b25df4cab166a611834ebf4158daf5c2855886",
      "to": "0x00fa2a5279f8f0fd2f0f9d3280ad70403f01f9d62f52373833",
      "value": 1000000,
      "transaction": "592e362bd16e11efe576f1cdcdc04fee7f0180f7e999678a1d858a98e558f42a",
      "data": "",
      "timestamp": 1565045672,
      "type": "block",
      "blockNumber": 1328526,
      "blockIndex": 7,
      "signature": "3046022100e97406cc8527a0d88d5e80928d6e0da9aa2e442c7a5844370fb130dfc210678e022100bb8459d4ae56b980666049df910fb8ac1032286f83757470fb53d633e4150e92",
      "publickey": "3059301306072a8648ce3d020106082a8648ce3d0301070342000458f1c1b9c923cb1c52e35c35b647f80518e738eb69fe06cb2af77d7c2f0ab28cd0b8cab4231ac3b1aa61ec2d0c4ed8bd9714fac83513a170c5fe8bd3d970db7c",
      "fee": 0,
      "realFee": 0,
      "nonce": 14,
      "intStatus": 20,
      "status": "ok"
    },
....
}
```
Метод `fetch-history-filter`
```JSON
POST http://tor.net-main.metahashnetwork.com:5795
{
    "id": 1,
    "jsonrpc": "2.0",
    "method": "fetch-history-filter",
    "params": {
        "address": "0x002a3e8f2714b25df4cab166a611834ebf4158daf5c2855886",
        "filters": [
            {
                "isForging": true
            }
        ]
    }
}
// response
{
  "id": 1,
  "error": {
    "code": -32602,
    "message": "Incorrect json. Error at file /home/user/torrent-node/common_utils/jsonUtils.h line 101. Url: /"
  }
}
```

**Comment by xboston** [comment]
И да, в коде фуллноды метод `fetch-history-filter` отсутствует https://github.com/metahashorg/metahash-fullnode-client/blob/master/src/task_handlers/task_handlers.cpp

**Comment by sv-91** [comment]
этот фильтр добавляет транзакции форджинга к выводу, если они там есть

**Comment by xboston** [comment]
Метод фильтра добавляет? Вот это поворот.

А есть ли возможность "фильтровать" транзакции по типу? Т.е. мне нужны транзакции только с наградами или только делегации или только isOutput, только они, никаких других.

**Comment by sv-91** [comment]
Если только isOutput, то можно в фильтре указать только isOutput. Фильтры делятся на 2 типа, включающие и исключающие

**Comment by xboston** [comment]
```json
{
    "id": 1,
    "jsonrpc": "2.0",
    "method": "fetch-history",
    "params": {
        "address": "0x00fa2a5279f8f0fd2f0f9d3280ad70403f01f9d62f52373833",
        "filters": [
            {
                "isOutput": true
            }
        ]
    }
}
```

Меняю на `"isOutput": false` -  результат не меняется.

**Comment by sv-91** [comment]
Если указано isOutput: true и текущая транзакция не транзакция отправки, то она отбрасывается.

**Comment by xboston** [comment]
Вот результат запроса с ` "isOutput": true`, в выдаче есть первая - исходящая и вторая - входящая транзакции:
<img width="1314" alt="Снимок экрана 2019-08-15 в 13 45 31" src="https://user-images.githubusercontent.com/201306/63090131-fcc54e00-bf62-11e9-9153-00ee8960930e.png">

**Comment by sv-91** [comment]
Метод называется 
fetch-history-filter
а не просто 
fetch-history

**Comment by xboston** [comment]
В таком случае отображается ошибка разбора JSON:
```json
{
  "id": 1,
  "error": {
    "code": -32602,
    "message": "Incorrect json. Error at file /home/user/torrent-node/common_utils/jsonUtils.h line 101. Url: /"
  }
}
```

**Comment by xboston** [comment]
Нашёл!
Вот такое сработало:
```json
{
    "id": 1,
    "jsonrpc": "2.0",
    "method": "fetch-history-filter",
    "params": {
        "address": "0x00fa2a5279f8f0fd2f0f9d3280ad70403f01f9d62f52373833",
        "filters": {
            "isOutput": true
        }
    }
}
```

**Comment by xboston** [comment]
В документации по методу всё перепутано https://github.com/metahashorg/metahash-fullnode-client/wiki/Usage#fetch-history-filter , составлю отдельный тикет про это и другие описания проверю.

**Comment by sv-91** [comment]
Нужен такой запрос. В документации ошибка
{"id":1,"params":{"address": "0x002a3e8f2714b25df4cab166a611834ebf4158daf5c2855886", "filters": {"isForging": true}},"method":"fetch-history-filter", "pretty": true}

**Comment by xboston** [comment]
Да, документация подвела.

Вынесите доки из wiki в статичные md страницы самого репозитория, тогда можно будет PR присылать с исправлениями.
