### ISSUE TITLE
Разная информация по транзакции в блоке и выдаче API

### ISSUE THREAD

**Issue by xboston** [metahashorg/MetaHash#4]
Есть блок https://venus.mhscan.com/?page=block&id=703916
В нём транзакция `f310137ce9c14f20a8623ba16224f29c34546ad28825aae78aa3fc6de8ecb37d`

Если скачать блок и посмотреть информацию по этой транзакции, то там будет:

```
            "delegate": 0,
            "isDelegate": false,
            "delegate_info": {
                "delegate": 0,
                "isDelegate": false
            },
            "status": "pending"
```

статус - pending, информации по разделегированию нет, delegateHash отсутствует.

Теперь смотрим эт же транзакцию через api: 
https://venus.mhscan.com/?page=tx&id=f310137ce9c14f20a8623ba16224f29c34546ad28825aae78aa3fc6de8ecb37d
или https://metawat.ch/txs/f310137ce9c14f20a8623ba16224f29c34546ad28825aae78aa3fc6de8ecb37d

Есть данные по сумме и delegationHash, а статус уже - OK

В следующем блоке нет уточняющей информации про эту транзакцию. Получается что если работать с блоками напрямую - то они не выдадут реальной информации по транзакции.

**Comment by Nikitaempower** [comment]
Проверьте, пожалуйста, остался ли вопрос нерешенным? @xboston

**Comment by xboston** [comment]
@Nikitaempower да! Теперь всё отлично, вопрос решён 👍
