### ISSUE TITLE
Пустые элементы там, где раньше были графики

### ISSUE THREAD

**Issue by xboston** [metahashorg/MetaHash#6]
В этих местах раньше иногда были графики курса соответствующей монеты, сейчас там пустота.

<img width="1136" alt="Снимок экрана 2019-05-29 в 21 42 05" src="https://user-images.githubusercontent.com/201306/58583471-c417b180-825c-11e9-9b15-5e1ad7d60cd6.png">

**Comment by Nikitaempower** [comment]
Будет исправлено в следующей версии приложения. Спасибо.
