### ISSUE TITLE
Черные квадратики на странице платежа

### ISSUE THREAD

**Issue by xboston** [metahashorg/MetaHash#7]
Они плохо заметны, но есть. При наведении отображается подсказка.

<img width="1136" alt="Снимок экрана 2019-05-29 в 21 46 01" src="https://user-images.githubusercontent.com/201306/58583539-f1645f80-825c-11e9-888f-e13ff1c99073.png">

**Comment by Nikitaempower** [comment]
Будет исправлено в следующей версии приложения. Спасибо.
